source 'https://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'rackup'
gem 'sinatra-cross_origin'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

group :development do
  gem 'pry'
  gem 'rerun'
end
